module.exports = {

  getAllProductSQL: "SELECT * FROM Productos",
  getProductByIdSQL: `SELECT * FROM Productos WHERE ID = @ID`,
  deleteProductSQL: `UPDATE Productos SET ACTIVO = 0 WHERE ID = @ID`,
  createProductSQL: `INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVO) 
  VALUES (@NOMBRE, @DESCRIPCION, @CATEGORIA, @PRECIO, @ACTIVO)`,
  updateProductSQL: `UPDATE Productos 
  SET NOMBRE = @NOMBRE, DESCRIPCION = @DESCRIPCION, CATEGORIA = @CATEGORIA, PRECIO = @PRECIO, ACTIVO = @ACTIVO
  WHERE ID = @ID`,
  getAuthUser: "SELECT * FROM USUARIOS WHERE MAIL = @EMAIL",
  getAllStock: "SELECT * FROM STOCK"
};
