IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'ASGP_DB')
BEGIN
    CREATE DATABASE ASGP_DB;
END;
GO

USE ASGP_DB;
GO

-- Tabla principal (no depende de otras)
CREATE TABLE PRODUCTOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(255),
    CATEGORIA VARCHAR(100),
    PRECIO DECIMAL(10, 2) NOT NULL,
    ACTIVE BIT NOT NULL DEFAULT 1
);
GO

-- Tabla principal (no depende de otras)
CREATE TABLE USUARIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_COMPLETO VARCHAR(255) NOT NULL,
    MAIL VARCHAR(255) NOT NULL UNIQUE,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    ROL VARCHAR(10) NOT NULL CHECK (ROL IN ('ADMIN', 'EMPLEADO'))
);
GO

-- Tabla STOCK: Se relaciona con PRODUCTOS
CREATE TABLE STOCK (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL UNIQUE,
    CANTIDAD_DEPOSITO INT DEFAULT 0,
    CANTIDAD_SUCURSAL INT DEFAULT 0,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) -- Relación con PRODUCTOS
);
GO

-- Tabla CIERRE_CAJA: Se relaciona con USUARIOS
CREATE TABLE CIERRE_CAJA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    FECHA_APERTURA DATETIME NOT NULL,
    FECHA_CIERRE DATETIME,
    MONTO_FINAL DECIMAL(10, 2),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES USUARIOS(ID) -- Relación con USUARIOS
);
GO

-- Tabla VENTAS: Se relaciona con USUARIOS y PRODUCTOS
CREATE TABLE VENTAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT GETDATE(),
    NUMERO_VENTA VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID), -- Relación con USUARIOS
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) -- Relación con PRODUCTOS
);
GO

-- INSERTS DE EJEMPLO PARA LA TABLA USUARIOS

INSERT INTO USUARIOS (NOMBRE_COMPLETO, MAIL, CONTRASEÑA, ROL) VALUES ('Facundo', 'facundo@gmail.com', 'dofacun123', 'ADMIN');
INSERT INTO USUARIOS (NOMBRE_COMPLETO, MAIL, CONTRASEÑA, ROL) VALUES ('Cristian', 'cristian@gmail.com', 'cristian123', 'ADMIN');
INSERT INTO USUARIOS (NOMBRE_COMPLETO, MAIL, CONTRASEÑA, ROL) VALUES ('Gustavo', 'gustavo@gmail.com', 'gustavo123', 'ADMIN');
INSERT INTO USUARIOS (NOMBRE_COMPLETO, MAIL, CONTRASEÑA, ROL) VALUES ('Julian', 'julian@gmail.com', 'julian123', 'ADMIN');
INSERT INTO USUARIOS (NOMBRE_COMPLETO, MAIL, CONTRASEÑA, ROL) VALUES ('Iara', 'iara@gmail.com', 'iara123', 'ADMIN');
INSERT INTO USUARIOS (NOMBRE_COMPLETO, MAIL, CONTRASEÑA, ROL) VALUES ('Carlos', 'empleado@gmail.com', 'empleado123', 'EMPLEADO');

-- INSERTS DE EJEMPLO PARA LA TABLA PRODUCTOS

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('AGUILA BROWNIE', 'UN ALFAJOR', 'ALFAJOR', '100',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('JORGITO BLANCO', 'UN ALFAJOR', 'ALFAJOR', '100',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('JORGITO NEGRO', 'UN ALFAJOR', 'ALFAJOR', '100',0)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('GUAYMALLEN SIMPLE NEGRO', 'UN ALFAJOR', 'ALFAJOR', '100',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('GUAYMALLEN SIMPLE BLANCO', 'UN ALFAJOR', 'ALFAJOR', '100',0)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('RED POINT 20', 'CIGARRILLO COMUN', 'CIGARILLO', '400',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('MARLBORO 20', 'CIGARRILLO COMUN', 'CIGARILLO', '400',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('CHESTERFIELD 20', 'CIGARRILLO COMUN', 'CIGARILLO', '400',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('PHILIP MORRIS 20', 'CIGARRILLO COMUN', 'CIGARILLO', '400',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('MASTER 20', 'CIGARRILLO COMUN', 'CIGARILLO', '400',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('COCA-COLA 2.25L', 'Coca-Cola 2 Litros', 'BEBIDA', '500',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('Pepsi 2.25L', 'Pepsi 2 Litros', 'BEBIDA', '500',0)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('Manaos 2.25L', 'Manaos 2 Litros', 'BEBIDA', '500',0)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('Agua 2.25L', 'Agua 2 Litros', 'BEBIDA', '500',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('Don satur Dulces', 'Don Satur Dulces Cuadradas', 'Galletitas', '125',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('Pepitos', 'Galletitas Pepitos', 'Galletitas', '125',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('Melba', 'Galletitas Melba', 'Galletitas', '125',1)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, CATEGORIA, PRECIO, ACTIVE) VALUES ('Oreo', 'Galletitas Oreo', 'Galletitas', '125',0)

-- INSERTS DE EJEMPLO PARA LA TABLA STOCK

INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (1, 100, 20);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (2, 57, 12);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (3, 220, 25);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (4, 33, 7);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (5, 88, 15);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (6, 142, 30);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (7, 65, 18);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (8, 190, 22);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (9, 78, 10);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (10, 55, 8);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (11, 210, 40);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (12, 120, 25);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (13, 95, 20);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (14, 130, 30);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (15, 160, 35);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (16, 70, 15);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (17, 185, 28);
INSERT INTO STOCK (ID_PRODUCTO, CANTIDAD_DEPOSITO, CANTIDAD_SUCURSAL) VALUES (18, 90, 12);
 
-- INSERTS DE EJEMPLO PARA LA TABLA VENTAS

INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (6, 1, 2, 100, 200, GETDATE(), 'VENTA-0001');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (2, 11, 1, 500, 500, GETDATE(), 'VENTA-0002');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (1, 17, 3, 125, 375, DATEADD(DAY, -1, GETDATE()), 'VENTA-0003');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (3, 16, 1, 125, 125, DATEADD(DAY, -2, GETDATE()), 'VENTA-0004');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (3, 18, 2, 125, 250, DATEADD(DAY, -2, GETDATE()), 'VENTA-0005');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (4, 7, 1, 400, 400, DATEADD(DAY, -3, GETDATE()), 'VENTA-0006');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (4, 6, 1, 400, 400, DATEADD(DAY, -3, GETDATE()), 'VENTA-0007');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (5, 4, 5, 100, 500, DATEADD(DAY, -5, GETDATE()), 'VENTA-0008');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (6, 14, 2, 500, 1000, GETDATE(), 'VENTA-0009');
INSERT INTO VENTAS (ID_USUARIO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, FECHA, NUMERO_VENTA)
VALUES (6, 11, 3, 500, 1500, GETDATE(), 'VENTA-0010');
GO